modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/PartyParrots/issues"

[[mods]]
    modId="partyparrots"
    version="${file.jarVersion}" #mandatory
    displayName="Party Parrots"
    displayURL="https://ichun.me/"
    authors="iChun"
    description='''
    Don't matter that there's no music, parrots wanna party!

    Dance parrot, dance!
    '''

[[dependencies.partyparrots]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.partyparrots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
