modLoader="javafml"
loaderVersion="[41,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/PartyParrots/issues"

[[mods]]
    modId="partyparrots"
    version="${file.jarVersion}" #mandatory
    displayName="Party Parrots"
    displayURL="https://ichun.me/"
    authors="iChun"
    description='''
    Don't matter that there's no music, parrots wanna party!

    Dance parrot, dance!
    '''

[[dependencies.partyparrots]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.partyparrots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
